# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9943d512b7f5e19349ea7d59bfb109facef79301e8b1c85cbe0c911a6a37023f49c369416f490ae03cb78ea5b6c0b94b5a70fe14ed481a78949a0bd7e0083c

test:
  secret_key_base: 80677a479a0649620f1e2be6fc9cfb25a0a539800aa5d81ac24c041c9d695fbdd5e23147fada179221384839aaa58ceda93f0f511c610ae08417c113e230d240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
